# Generated by Django 4.1.2 on 2022-10-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnglishSchemeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("desc", models.TextField(blank=True, null=True)),
                ("income_limit", models.TextField(blank=True, null=True)),
                ("interest_rate", models.TextField(blank=True, null=True)),
                ("extra_data", models.TextField(blank=True, null=True)),
                ("caste", models.CharField(blank=True, max_length=255, null=True)),
                ("religion", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("min_age", models.IntegerField(blank=True, null=True)),
                ("max_age", models.IntegerField(blank=True, null=True)),
                ("min_inc", models.IntegerField(blank=True, null=True)),
                ("max_inc", models.IntegerField(blank=True, null=True)),
                ("eduaction", models.CharField(blank=True, max_length=255, null=True)),
                ("occuptaion", models.CharField(blank=True, max_length=255, null=True)),
                ("disability", models.CharField(blank=True, max_length=255, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GujSchemeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("desc", models.TextField(blank=True, null=True)),
                ("income", models.TextField(blank=True, null=True)),
                ("interest_rate", models.TextField(blank=True, null=True)),
                ("extra_data", models.TextField(blank=True, null=True)),
                ("caste", models.CharField(blank=True, max_length=255, null=True)),
                ("religion", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("min_age", models.IntegerField(blank=True, null=True)),
                ("max_age", models.IntegerField(blank=True, null=True)),
                ("min_inc", models.IntegerField(blank=True, null=True)),
                ("max_inc", models.IntegerField(blank=True, null=True)),
                ("eduaction", models.CharField(blank=True, max_length=255, null=True)),
                ("occuptaion", models.CharField(blank=True, max_length=255, null=True)),
                ("disability", models.CharField(blank=True, max_length=255, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
