# Generated by Django 4.1.2 on 2022-10-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="englishschememodel",
            name="extra_data",
        ),
        migrations.RemoveField(
            model_name="gujschememodel",
            name="extra_data",
        ),
        migrations.AddField(
            model_name="englishschememodel",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gujschememodel",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
