# Generated by Django 4.1.2 on 2022-10-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_rename_occuptaion_englishschememodel_occupation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gujschememodel',
            old_name='eduaction',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='gujschememodel',
            old_name='occuptaion',
            new_name='occupation',
        ),
    ]
