# Generated by Django 4.1.2 on 2022-10-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_rename_eduaction_gujschememodel_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishschememodel',
            name='educational_qualifications',
            field=models.IntegerField(blank=True, choices=[(3, 'Graduate'), (2, 'Under Graduate'), (1, 'Schooling'), (0, 'Not Applicable')], null=True),
        ),
    ]
