# Generated by Django 4.1.2 on 2022-10-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="caste",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="educational_qualifications",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="income",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
