# Generated by Django 4.1.2 on 2022-10-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_caste_alter_user_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="educational_qualifications",
            field=models.CharField(
                choices=[
                    ("Graduate", "Graduate"),
                    ("Not Applicable", "Uneducated"),
                    ("Under Graduate", "Under Graduate"),
                    ("Schooling", "In School"),
                ],
                default="Graduate",
                max_length=15,
            ),
        ),
    ]
