# Generated by Django 4.1.2 on 2022-10-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(auto_now_add=True),
        ),
    ]
