# Generated by Django 4.1.2 on 2022-10-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
