# Generated by Django 4.1.2 on 2022-10-16 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_educational_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='educational_qualifications',
            field=models.CharField(choices=[(3, 'Graduate'), (2, 'Under Graduate'), (1, 'Schooling'), (0, 'Not Applicable')], default='Graduate', max_length=15),
        ),
    ]
